In [11]:
import pandas as pd
import os
import numpy as np
import datetime as dt
from filter_foia import filter_foia


cwd = os.getcwd()
cwd

'C:\\Users\\OITNYNWilsoS\\OneDrive - Department of Veterans Affairs\\python\\FOIA\\FOIA metrics - Tammy\\2025 Cleland-Dole Act Report'

In [12]:
agency = 'Department of Veterans Affairs'
entity = 'VA'

processed_received = pd.read_csv("2024 all federal agencies foia-received-processed-and-pending-foia-requests.csv")
keep_cols = ['Fiscal Year', 'Number of Requests Received in Fiscal Year', 'Number of Requests Processed in Fiscal Year']
va_vol = filter_foia(processed_received, agency, keep_cols, entity)
va_vol.loc[len(va_vol)] = [dt.datetime(2025,1,1), 123789, 122552] #from 2025 Annual Report
va_vol

,Fiscal Year,VA Number of Requests Received in Fiscal Year,VA Number of Requests Processed in Fiscal Year
0,2013-01-01,25647,26376
1,2014-01-01,28009,27982
2,2015-01-01,29716,30436
3,2016-01-01,34459,33313
4,2017-01-01,24176,25237
5,2018-01-01,24555,22851
6,2019-01-01,21336,23749
7,2020-01-01,19053,19323
8,2021-01-01,27762,30227
9,2022-01-01,22542,24343
10,2023-01-01,79590,72403
11,2024-01-01,105725,119453
12,2025-01-01,123789,122552

In [13]:
va_vol = va_vol.sort_values('Fiscal Year', ascending=True)
va_vol['Increase Requests Processed'] = va_vol['VA Number of Requests Processed in Fiscal Year'].diff()
va_vol

,Fiscal Year,VA Number of Requests Received in Fiscal Year,VA Number of Requests Processed in Fiscal Year,Increase Requests Processed
0,2013-01-01,25647,26376,NaN
1,2014-01-01,28009,27982,1606.0
2,2015-01-01,29716,30436,2454.0
3,2016-01-01,34459,33313,2877.0
4,2017-01-01,24176,25237,-8076.0
5,2018-01-01,24555,22851,-2386.0
6,2019-01-01,21336,23749,898.0
7,2020-01-01,19053,19323,-4426.0
8,2021-01-01,27762,30227,10904.0
9,2022-01-01,22542,24343,-5884.0
10,2023-01-01,79590,72403,48060.0
11,2024-01-01,105725,119453,47050.0
12,2025-01-01,123789,122552,3099.0

In [15]:
score_card_folder = r"C:\Users\OITNYNWilsoS\OneDrive - Department of Veterans Affairs\CRR Data Analytics (FOIA) - eFOIA\Score Card Power BI dashboards/"

with pd.ExcelWriter(
    "va volume.xlsx",
    engine="xlsxwriter",
    date_format="YYYY-MM-DD",
    datetime_format="YYYY-MM-DD"
) as writer:
    va_vol.to_excel(os.path.join(score_card_folder, "va volume.xlsx"), sheet_name="VA Volume", index=False)